#!/bin/bash

psql <<EOF
CREATE USER $KEYCLOAK_DB_USER WITH PASSWORD '$KEYCLOAK_DB_PASS';
CREATE DATABASE $KEYCLOAK_DB_NAME;
GRANT ALL PRIVILEGES ON DATABASE $KEYCLOAK_DB_NAME TO $KEYCLOAK_DB_USER;
EOF
